title: Rescue Mobile
tagline: App for organsing rescue events
email: intive@intive.com
description: >
  The demo site for Bulma Clean Theme, made for Jekyll and GitHub pages websites
baseurl: "/RescueMobileIntiative"
url: "http://masztalski.github.io"
permalink: pretty
#theme: bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme
languages: ["en", "pl"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css"]
parallel_localization: false

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
  - github-pages
  - jekyll-polyglot